baseURL = "/"
languageCode = "vi"
title = "Blog Lập Trình"

[params]
  description = "Chia sẻ kiến thức về Java và JavaScript"
  author = "Hải Quý"
  
  [params.colors]
    primary = "#002044"
    accent = "#ff7760"
    highlight = "#9de2ea"
    background = "#f9f9f9"
  
  [params.typography]
    body_font = "Poppins, -apple-system, sans-serif"
    heading_font = "Poppins, sans-serif"
  
  [params.header]
    layout = "sticky"
    height = "80px"
    logo_text = "HaiQuy.Tech"
  
  [params.social]
    email = "quysun2356@gmail.com"
    facebook = "https://www.facebook.com/HaiQuyThatTha24092003"
    tiktok = "https://www.tiktok.com/@boiboi_249"
    youtube = "https://www.youtube.com/@haiquythattha12a97"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Java"
    url = "/categories/java/"
    weight = 2
  [[menu.main]]
    name = "JavaScript"
    url = "/categories/javascript/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = true
    lineNumbersInTable = true