baseURL = "https://foxy203.github.io/hugo-blog-hai-quy/"
languageCode = "vi"
title = "Blog Lập Trình"

# QUAN TRỌNG: Cấu hình này giúp web chạy được cả trên Local và GitHub Pages
relativeURLs = true
canonifyURLs = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  description = "Chia sẻ kiến thức về Java và JavaScript"
  
  [params.author]
    name = "Hải Quý"
    email = "quysun2356@gmail.com"
  
  [params.colors]
    primary = "#002044"
    accent = "#ff7760"
    highlight = "#9de2ea"
    background = "#f9f9f9"
  
  [params.header]
    layout = "sticky"
    height = "80px"
    logo_text = "HaiQuy.Tech"
  
  [params.social]
    email = "quysun2356@gmail.com"
    facebook = "https://www.facebook.com/HaiQuyThatTha24092003"
    tiktok = "https://www.tiktok.com/@boiboi_249"
    youtube = "https://www.youtube.com/@haiquythattha12a97"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Java"
    url = "/categories/java/"
    weight = 2
  [[menu.main]]
    name = "JavaScript"
    url = "/categories/javascript/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    tabWidth = 4